CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520162536_InitialCreate') THEN
    CREATE TABLE "PB_Persona" (
        "IDPersona" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" character varying(150) NOT NULL,
        "Apellido" character varying(150) NOT NULL,
        "FechaNacimiento" timestamp without time zone NOT NULL,
        "Dni" character varying(20) NOT NULL,
        "Email" character varying(250),
        "Celular" character varying(50),
        CONSTRAINT "PK_PB_Persona" PRIMARY KEY ("IDPersona")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520162536_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_PB_Persona_Dni" ON "PB_Persona" ("Dni");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520162536_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_PB_Persona_Email" ON "PB_Persona" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520162536_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260520162536_InitialCreate', '10.0.0');
    END IF;
END $EF$;
COMMIT;

