CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520162536_InitialCreate') THEN
    CREATE TABLE "PB_Persona" (
        "IDPersona" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" character varying(150) NOT NULL,
        "Apellido" character varying(150) NOT NULL,
        "FechaNacimiento" timestamp without time zone NOT NULL,
        "Dni" character varying(20) NOT NULL,
        "Email" character varying(250),
        "Celular" character varying(50),
        CONSTRAINT "PK_PB_Persona" PRIMARY KEY ("IDPersona")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520162536_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_PB_Persona_Dni" ON "PB_Persona" ("Dni");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520162536_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_PB_Persona_Email" ON "PB_Persona" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520162536_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260520162536_InitialCreate', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260604183100_AddUsuarioEntity') THEN
    CREATE TABLE "PB_Usuario" (
        "IDUsuario" integer GENERATED BY DEFAULT AS IDENTITY,
        "Username" character varying(100) NOT NULL,
        "Password" character varying(255) NOT NULL,
        "Email" character varying(250) NOT NULL,
        "Activo" boolean NOT NULL DEFAULT TRUE,
        "IDPersona" integer NOT NULL,
        CONSTRAINT "PK_PB_Usuario" PRIMARY KEY ("IDUsuario"),
        CONSTRAINT "FK_PB_Usuario_PB_Persona_IDPersona" FOREIGN KEY ("IDPersona") REFERENCES "PB_Persona" ("IDPersona") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260604183100_AddUsuarioEntity') THEN
    CREATE UNIQUE INDEX "IX_PB_Usuario_Email" ON "PB_Usuario" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260604183100_AddUsuarioEntity') THEN
    CREATE INDEX "IX_PB_Usuario_IDPersona" ON "PB_Usuario" ("IDPersona");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260604183100_AddUsuarioEntity') THEN
    CREATE UNIQUE INDEX "IX_PB_Usuario_Username" ON "PB_Usuario" ("Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260604183100_AddUsuarioEntity') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260604183100_AddUsuarioEntity', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260605115341_RemoveIDPersonaFromUsuario') THEN
    ALTER TABLE "PB_Usuario" DROP CONSTRAINT "FK_PB_Usuario_PB_Persona_IDPersona";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260605115341_RemoveIDPersonaFromUsuario') THEN
    DROP INDEX "IX_PB_Usuario_IDPersona";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260605115341_RemoveIDPersonaFromUsuario') THEN
    ALTER TABLE "PB_Usuario" DROP COLUMN "IDPersona";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260605115341_RemoveIDPersonaFromUsuario') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260605115341_RemoveIDPersonaFromUsuario', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260605130045_SeedUsuariosIniciales') THEN

                    INSERT INTO "PB_Usuario" ("Username", "Password", "Email", "Activo")
                    SELECT 'seba', '123', 'seba@proyectobase.com', true
                    WHERE NOT EXISTS (SELECT 1 FROM "PB_Usuario" WHERE "Username" = 'seba');

                    INSERT INTO "PB_Usuario" ("Username", "Password", "Email", "Activo")
                    SELECT 'julian', '123', 'julian@proyectobase.com', true
                    WHERE NOT EXISTS (SELECT 1 FROM "PB_Usuario" WHERE "Username" = 'julian');

                    INSERT INTO "PB_Usuario" ("Username", "Password", "Email", "Activo")
                    SELECT 'juancruz', '123', 'juancruz@proyectobase.com', true
                    WHERE NOT EXISTS (SELECT 1 FROM "PB_Usuario" WHERE "Username" = 'juancruz');
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260605130045_SeedUsuariosIniciales') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260605130045_SeedUsuariosIniciales', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260617134138_CU08_ConsorcioComplejoDomain') THEN
    CREATE TABLE "PB_Consorcio" (
        "IDConsorcio" integer GENERATED BY DEFAULT AS IDENTITY,
        "Cuit" character varying(11) NOT NULL,
        "Nombre" character varying(100) NOT NULL,
        "Email" character varying(100) NOT NULL,
        "Telefono" character varying(20),
        CONSTRAINT "PK_PB_Consorcio" PRIMARY KEY ("IDConsorcio")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260617134138_CU08_ConsorcioComplejoDomain') THEN
    CREATE TABLE "PB_Complejo" (
        "IDComplejo" integer GENERATED BY DEFAULT AS IDENTITY,
        "IDConsorcio" integer NOT NULL,
        "Nombre" character varying(100) NOT NULL,
        "Tipo" character varying(20) NOT NULL,
        "Direccion" character varying(200) NOT NULL,
        CONSTRAINT "PK_PB_Complejo" PRIMARY KEY ("IDComplejo"),
        CONSTRAINT "FK_PB_Complejo_PB_Consorcio_IDConsorcio" FOREIGN KEY ("IDConsorcio") REFERENCES "PB_Consorcio" ("IDConsorcio") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260617134138_CU08_ConsorcioComplejoDomain') THEN
    CREATE UNIQUE INDEX "IX_PB_Complejo_IDConsorcio_Nombre" ON "PB_Complejo" ("IDConsorcio", "Nombre");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260617134138_CU08_ConsorcioComplejoDomain') THEN
    CREATE UNIQUE INDEX "IX_PB_Consorcio_Cuit" ON "PB_Consorcio" ("Cuit");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260617134138_CU08_ConsorcioComplejoDomain') THEN
    CREATE UNIQUE INDEX "IX_PB_Consorcio_Email" ON "PB_Consorcio" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260617134138_CU08_ConsorcioComplejoDomain') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260617134138_CU08_ConsorcioComplejoDomain', '10.0.0');
    END IF;
END $EF$;
COMMIT;

