CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520162536_InitialCreate') THEN
    CREATE TABLE "PB_Persona" (
        "IDPersona" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" character varying(150) NOT NULL,
        "Apellido" character varying(150) NOT NULL,
        "FechaNacimiento" timestamp without time zone NOT NULL,
        "Dni" character varying(20) NOT NULL,
        "Email" character varying(250),
        "Celular" character varying(50),
        CONSTRAINT "PK_PB_Persona" PRIMARY KEY ("IDPersona")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520162536_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_PB_Persona_Dni" ON "PB_Persona" ("Dni");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520162536_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_PB_Persona_Email" ON "PB_Persona" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520162536_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260520162536_InitialCreate', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260604183100_AddUsuarioEntity') THEN
    CREATE TABLE "PB_Usuario" (
        "IDUsuario" integer GENERATED BY DEFAULT AS IDENTITY,
        "Username" character varying(100) NOT NULL,
        "Password" character varying(255) NOT NULL,
        "Email" character varying(250) NOT NULL,
        "Activo" boolean NOT NULL DEFAULT TRUE,
        "IDPersona" integer NOT NULL,
        CONSTRAINT "PK_PB_Usuario" PRIMARY KEY ("IDUsuario"),
        CONSTRAINT "FK_PB_Usuario_PB_Persona_IDPersona" FOREIGN KEY ("IDPersona") REFERENCES "PB_Persona" ("IDPersona") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260604183100_AddUsuarioEntity') THEN
    CREATE UNIQUE INDEX "IX_PB_Usuario_Email" ON "PB_Usuario" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260604183100_AddUsuarioEntity') THEN
    CREATE INDEX "IX_PB_Usuario_IDPersona" ON "PB_Usuario" ("IDPersona");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260604183100_AddUsuarioEntity') THEN
    CREATE UNIQUE INDEX "IX_PB_Usuario_Username" ON "PB_Usuario" ("Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260604183100_AddUsuarioEntity') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260604183100_AddUsuarioEntity', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260605115341_RemoveIDPersonaFromUsuario') THEN
    ALTER TABLE "PB_Usuario" DROP CONSTRAINT "FK_PB_Usuario_PB_Persona_IDPersona";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260605115341_RemoveIDPersonaFromUsuario') THEN
    DROP INDEX "IX_PB_Usuario_IDPersona";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260605115341_RemoveIDPersonaFromUsuario') THEN
    ALTER TABLE "PB_Usuario" DROP COLUMN "IDPersona";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260605115341_RemoveIDPersonaFromUsuario') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260605115341_RemoveIDPersonaFromUsuario', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260605130045_SeedUsuariosIniciales') THEN

                    INSERT INTO "PB_Usuario" ("Username", "Password", "Email", "Activo")
                    SELECT 'seba', '123', 'seba@proyectobase.com', true
                    WHERE NOT EXISTS (SELECT 1 FROM "PB_Usuario" WHERE "Username" = 'seba');

                    INSERT INTO "PB_Usuario" ("Username", "Password", "Email", "Activo")
                    SELECT 'julian', '123', 'julian@proyectobase.com', true
                    WHERE NOT EXISTS (SELECT 1 FROM "PB_Usuario" WHERE "Username" = 'julian');

                    INSERT INTO "PB_Usuario" ("Username", "Password", "Email", "Activo")
                    SELECT 'juancruz', '123', 'juancruz@proyectobase.com', true
                    WHERE NOT EXISTS (SELECT 1 FROM "PB_Usuario" WHERE "Username" = 'juancruz');
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260605130045_SeedUsuariosIniciales') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260605130045_SeedUsuariosIniciales', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260617134138_CU08_ConsorcioComplejoDomain') THEN
    CREATE TABLE "PB_Consorcio" (
        "IDConsorcio" integer GENERATED BY DEFAULT AS IDENTITY,
        "Cuit" character varying(11) NOT NULL,
        "Nombre" character varying(100) NOT NULL,
        "Email" character varying(100) NOT NULL,
        "Telefono" character varying(20),
        CONSTRAINT "PK_PB_Consorcio" PRIMARY KEY ("IDConsorcio")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260617134138_CU08_ConsorcioComplejoDomain') THEN
    CREATE TABLE "PB_Complejo" (
        "IDComplejo" integer GENERATED BY DEFAULT AS IDENTITY,
        "IDConsorcio" integer NOT NULL,
        "Nombre" character varying(100) NOT NULL,
        "Tipo" character varying(20) NOT NULL,
        "Direccion" character varying(200) NOT NULL,
        CONSTRAINT "PK_PB_Complejo" PRIMARY KEY ("IDComplejo"),
        CONSTRAINT "FK_PB_Complejo_PB_Consorcio_IDConsorcio" FOREIGN KEY ("IDConsorcio") REFERENCES "PB_Consorcio" ("IDConsorcio") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260617134138_CU08_ConsorcioComplejoDomain') THEN
    CREATE UNIQUE INDEX "IX_PB_Complejo_IDConsorcio_Nombre" ON "PB_Complejo" ("IDConsorcio", "Nombre");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260617134138_CU08_ConsorcioComplejoDomain') THEN
    CREATE UNIQUE INDEX "IX_PB_Consorcio_Cuit" ON "PB_Consorcio" ("Cuit");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260617134138_CU08_ConsorcioComplejoDomain') THEN
    CREATE UNIQUE INDEX "IX_PB_Consorcio_Email" ON "PB_Consorcio" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260617134138_CU08_ConsorcioComplejoDomain') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260617134138_CU08_ConsorcioComplejoDomain', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260617173829_SeedConsorcioComplejoPrueba') THEN

                    INSERT INTO "PB_Consorcio" ("Cuit", "Nombre", "Email", "Telefono") 
                    VALUES ('11111111111', 'Consorcio Alfa', 'alfa@consorcio.com', '123456') 
                    ON CONFLICT ("Cuit") DO NOTHING;

                    INSERT INTO "PB_Consorcio" ("Cuit", "Nombre", "Email", "Telefono") 
                    VALUES ('22222222222', 'Consorcio Beta', 'beta@consorcio.com', '654321') 
                    ON CONFLICT ("Cuit") DO NOTHING;

                    INSERT INTO "PB_Complejo" ("IDConsorcio", "Nombre", "Tipo", "Direccion") 
                    SELECT "IDConsorcio", 'Torre Alfa Norte', 'EDIFICIO', 'Avenida Norte 100' 
                    FROM "PB_Consorcio" WHERE "Cuit" = '11111111111' 
                    ON CONFLICT ("IDConsorcio", "Nombre") DO NOTHING;

                    INSERT INTO "PB_Complejo" ("IDConsorcio", "Nombre", "Tipo", "Direccion") 
                    SELECT "IDConsorcio", 'Barrio Beta Sur', 'BARRIO_PRIVADO', 'Ruta Sur 200' 
                    FROM "PB_Consorcio" WHERE "Cuit" = '22222222222' 
                    ON CONFLICT ("IDConsorcio", "Nombre") DO NOTHING;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260617173829_SeedConsorcioComplejoPrueba') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260617173829_SeedConsorcioComplejoPrueba', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702175644_Etapa2_Entidades') THEN
    CREATE TABLE "PB_Amenity" (
        "IDAmenity" integer GENERATED BY DEFAULT AS IDENTITY,
        "IDComplejo" integer NOT NULL,
        "Nombre" character varying(50) NOT NULL,
        "Capacidad" integer NOT NULL,
        "Estado" character varying(20) NOT NULL DEFAULT 'DISPONIBLE',
        CONSTRAINT "PK_PB_Amenity" PRIMARY KEY ("IDAmenity"),
        CONSTRAINT "FK_PB_Amenity_PB_Complejo_IDComplejo" FOREIGN KEY ("IDComplejo") REFERENCES "PB_Complejo" ("IDComplejo") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702175644_Etapa2_Entidades') THEN
    CREATE TABLE "PB_UnidadHabitacional" (
        "IDUnidadHabitacional" integer GENERATED BY DEFAULT AS IDENTITY,
        "IDComplejo" integer NOT NULL,
        "Identificador" character varying(20) NOT NULL,
        "DebeExpensas" boolean NOT NULL DEFAULT FALSE,
        "SaldoActual" numeric(12,2) NOT NULL DEFAULT 0.0,
        "EstadoUnidad" character varying(15) NOT NULL DEFAULT 'ACTIVA',
        "ContadorInfracciones" integer NOT NULL DEFAULT 0,
        CONSTRAINT "PK_PB_UnidadHabitacional" PRIMARY KEY ("IDUnidadHabitacional"),
        CONSTRAINT "FK_PB_UnidadHabitacional_PB_Complejo_IDComplejo" FOREIGN KEY ("IDComplejo") REFERENCES "PB_Complejo" ("IDComplejo") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702175644_Etapa2_Entidades') THEN
    CREATE TABLE "PB_AmenityConfig" (
        "IDAmenityConfig" integer GENERATED BY DEFAULT AS IDENTITY,
        "IDAmenity" integer NOT NULL,
        "HorarioInicio" time NOT NULL,
        "HorarioFin" time NOT NULL,
        "DuracionBloqueMinutos" integer NOT NULL,
        "TiempoLimpiezaMinutos" integer NOT NULL DEFAULT 0,
        "Tarifa" numeric(10,2) NOT NULL DEFAULT 0.0,
        "LimiteReservasMesUnidad" integer NOT NULL,
        "RequiereAprobacion" boolean NOT NULL DEFAULT FALSE,
        CONSTRAINT "PK_PB_AmenityConfig" PRIMARY KEY ("IDAmenityConfig"),
        CONSTRAINT "FK_PB_AmenityConfig_PB_Amenity_IDAmenity" FOREIGN KEY ("IDAmenity") REFERENCES "PB_Amenity" ("IDAmenity") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702175644_Etapa2_Entidades') THEN
    CREATE TABLE "PB_Incidencia" (
        "IDIncidencia" integer GENERATED BY DEFAULT AS IDENTITY,
        "IDAmenity" integer NOT NULL,
        "IDUnidadHabitacional" integer NOT NULL,
        "Descripcion" character varying(500) NOT NULL,
        "Estado" character varying(20) NOT NULL,
        "DetalleResolucion" character varying(500),
        "CostoEstimado" numeric(10,2),
        "FechaReporte" timestamp with time zone NOT NULL,
        "FechaResolucion" timestamp with time zone,
        CONSTRAINT "PK_PB_Incidencia" PRIMARY KEY ("IDIncidencia"),
        CONSTRAINT "FK_PB_Incidencia_PB_Amenity_IDAmenity" FOREIGN KEY ("IDAmenity") REFERENCES "PB_Amenity" ("IDAmenity") ON DELETE RESTRICT,
        CONSTRAINT "FK_PB_Incidencia_PB_UnidadHabitacional_IDUnidadHabitacional" FOREIGN KEY ("IDUnidadHabitacional") REFERENCES "PB_UnidadHabitacional" ("IDUnidadHabitacional") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702175644_Etapa2_Entidades') THEN
    CREATE TABLE "PB_Inquilino" (
        "IDInquilino" integer GENERATED BY DEFAULT AS IDENTITY,
        "IDUnidadHabitacional" integer NOT NULL,
        "Nombre" character varying(100) NOT NULL,
        "Apellido" character varying(100) NOT NULL,
        "Dni" character varying(20) NOT NULL,
        "Telefono" character varying(20),
        "Activo" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_PB_Inquilino" PRIMARY KEY ("IDInquilino"),
        CONSTRAINT "FK_PB_Inquilino_PB_UnidadHabitacional_IDUnidadHabitacional" FOREIGN KEY ("IDUnidadHabitacional") REFERENCES "PB_UnidadHabitacional" ("IDUnidadHabitacional") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702175644_Etapa2_Entidades') THEN
    CREATE TABLE "PB_Invitado" (
        "IDInvitado" integer GENERATED BY DEFAULT AS IDENTITY,
        "IDUnidadHabitacional" integer NOT NULL,
        "Nombre" character varying(100) NOT NULL,
        "Apellido" character varying(100) NOT NULL,
        "Dni" character varying(20) NOT NULL,
        "EstadoAcceso" character varying(15) NOT NULL DEFAULT 'PERMITIDO',
        "HoraIngreso" timestamp with time zone,
        "HoraEgreso" timestamp with time zone,
        CONSTRAINT "PK_PB_Invitado" PRIMARY KEY ("IDInvitado"),
        CONSTRAINT "FK_PB_Invitado_PB_UnidadHabitacional_IDUnidadHabitacional" FOREIGN KEY ("IDUnidadHabitacional") REFERENCES "PB_UnidadHabitacional" ("IDUnidadHabitacional") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702175644_Etapa2_Entidades') THEN
    CREATE TABLE "PB_Reserva" (
        "IDReserva" integer GENERATED BY DEFAULT AS IDENTITY,
        "IDAmenity" integer NOT NULL,
        "IDUnidadHabitacional" integer NOT NULL,
        "FechaUso" date NOT NULL,
        "HoraInicio" time NOT NULL,
        "HoraFin" time NOT NULL,
        "CantidadInvitados" integer NOT NULL DEFAULT 0,
        "Estado" character varying(25) NOT NULL,
        "FechaSolicitud" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PB_Reserva" PRIMARY KEY ("IDReserva"),
        CONSTRAINT "FK_PB_Reserva_PB_Amenity_IDAmenity" FOREIGN KEY ("IDAmenity") REFERENCES "PB_Amenity" ("IDAmenity") ON DELETE RESTRICT,
        CONSTRAINT "FK_PB_Reserva_PB_UnidadHabitacional_IDUnidadHabitacional" FOREIGN KEY ("IDUnidadHabitacional") REFERENCES "PB_UnidadHabitacional" ("IDUnidadHabitacional") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702175644_Etapa2_Entidades') THEN
    CREATE UNIQUE INDEX "IX_PB_Amenity_IDComplejo_Nombre" ON "PB_Amenity" ("IDComplejo", "Nombre");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702175644_Etapa2_Entidades') THEN
    CREATE UNIQUE INDEX "IX_PB_AmenityConfig_IDAmenity" ON "PB_AmenityConfig" ("IDAmenity");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702175644_Etapa2_Entidades') THEN
    CREATE INDEX "IX_PB_Incidencia_IDAmenity" ON "PB_Incidencia" ("IDAmenity");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702175644_Etapa2_Entidades') THEN
    CREATE INDEX "IX_PB_Incidencia_IDUnidadHabitacional" ON "PB_Incidencia" ("IDUnidadHabitacional");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702175644_Etapa2_Entidades') THEN
    CREATE UNIQUE INDEX "IX_PB_Inquilino_Dni" ON "PB_Inquilino" ("Dni");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702175644_Etapa2_Entidades') THEN
    CREATE INDEX "IX_PB_Inquilino_IDUnidadHabitacional" ON "PB_Inquilino" ("IDUnidadHabitacional");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702175644_Etapa2_Entidades') THEN
    CREATE INDEX "IX_PB_Invitado_IDUnidadHabitacional" ON "PB_Invitado" ("IDUnidadHabitacional");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702175644_Etapa2_Entidades') THEN
    CREATE INDEX "IX_PB_Reserva_IDAmenity" ON "PB_Reserva" ("IDAmenity");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702175644_Etapa2_Entidades') THEN
    CREATE INDEX "IX_PB_Reserva_IDUnidadHabitacional" ON "PB_Reserva" ("IDUnidadHabitacional");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702175644_Etapa2_Entidades') THEN
    CREATE UNIQUE INDEX "IX_PB_UnidadHabitacional_IDComplejo_Identificador" ON "PB_UnidadHabitacional" ("IDComplejo", "Identificador");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702175644_Etapa2_Entidades') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260702175644_Etapa2_Entidades', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702184429_003_Etapa2_Fase1') THEN
    DROP TABLE "PB_Incidencia";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702184429_003_Etapa2_Fase1') THEN
    DROP TABLE "PB_Inquilino";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702184429_003_Etapa2_Fase1') THEN
    DROP TABLE "PB_Invitado";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702184429_003_Etapa2_Fase1') THEN
    DROP TABLE "PB_Reserva";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702184429_003_Etapa2_Fase1') THEN
    ALTER TABLE "PB_UnidadHabitacional" ALTER COLUMN "SaldoActual" TYPE numeric(18,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702184429_003_Etapa2_Fase1') THEN
    ALTER TABLE "PB_UnidadHabitacional" ALTER COLUMN "EstadoUnidad" TYPE character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702184429_003_Etapa2_Fase1') THEN
    ALTER TABLE "PB_AmenityConfig" ALTER COLUMN "Tarifa" TYPE numeric(18,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702184429_003_Etapa2_Fase1') THEN
    ALTER TABLE "PB_AmenityConfig" ALTER COLUMN "HorarioInicio" TYPE time without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702184429_003_Etapa2_Fase1') THEN
    ALTER TABLE "PB_AmenityConfig" ALTER COLUMN "HorarioFin" TYPE time without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702184429_003_Etapa2_Fase1') THEN
    ALTER TABLE "PB_Amenity" ALTER COLUMN "Nombre" TYPE character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702184429_003_Etapa2_Fase1') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260702184429_003_Etapa2_Fase1', '10.0.0');
    END IF;
END $EF$;
COMMIT;

