// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProyectoBase.Models;

#nullable disable

namespace ProyectoBase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260702185133_004_Etapa2_Fase2")]
    partial class _004_Etapa2_Fase2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProyectoBase.Models.Amenity", b =>
                {
                    b.Property<int>("IDAmenity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDAmenity"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("DISPONIBLE");

                    b.Property<int>("IDComplejo")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IDAmenity");

                    b.HasIndex("IDComplejo", "Nombre")
                        .IsUnique();

                    b.ToTable("PB_Amenity", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.AmenityConfig", b =>
                {
                    b.Property<int>("IDAmenityConfig")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDAmenityConfig"));

                    b.Property<int>("DuracionBloqueMinutos")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("HorarioFin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HorarioInicio")
                        .HasColumnType("time without time zone");

                    b.Property<int>("IDAmenity")
                        .HasColumnType("integer");

                    b.Property<int>("LimiteReservasMesUnidad")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiereAprobacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Tarifa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("TiempoLimpiezaMinutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("IDAmenityConfig");

                    b.HasIndex("IDAmenity")
                        .IsUnique();

                    b.ToTable("PB_AmenityConfig", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.Complejo", b =>
                {
                    b.Property<int>("IDComplejo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDComplejo"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("IDConsorcio")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IDComplejo");

                    b.HasIndex("IDConsorcio", "Nombre")
                        .IsUnique();

                    b.ToTable("PB_Complejo", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.Consorcio", b =>
                {
                    b.Property<int>("IDConsorcio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDConsorcio"));

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IDConsorcio");

                    b.HasIndex("Cuit")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("PB_Consorcio", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.Inquilino", b =>
                {
                    b.Property<int>("IDInquilino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDInquilino"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Celular")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("IDUnidadHabitacional")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("IDInquilino");

                    b.HasIndex("IDUnidadHabitacional");

                    b.ToTable("PB_Inquilino", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.Invitado", b =>
                {
                    b.Property<int>("IDInvitado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDInvitado"));

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("FechaExpiracion")
                        .HasColumnType("date");

                    b.Property<int>("IDUnidadHabitacional")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Patente")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IDInvitado");

                    b.HasIndex("IDUnidadHabitacional", "Dni")
                        .IsUnique();

                    b.ToTable("PB_Invitado", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.Persona", b =>
                {
                    b.Property<int>("IDPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDPersona"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Celular")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("IDPersona");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("PB_Persona", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.UnidadHabitacional", b =>
                {
                    b.Property<int>("IDUnidadHabitacional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDUnidadHabitacional"));

                    b.Property<int>("ContadorInfracciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("DebeExpensas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("EstadoUnidad")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ACTIVA");

                    b.Property<int>("IDComplejo")
                        .HasColumnType("integer");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("SaldoActual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("IDUnidadHabitacional");

                    b.HasIndex("IDComplejo", "Identificador")
                        .IsUnique();

                    b.ToTable("PB_UnidadHabitacional", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.Usuario", b =>
                {
                    b.Property<int>("IDUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDUsuario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IDUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("PB_Usuario", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.Amenity", b =>
                {
                    b.HasOne("ProyectoBase.Models.Complejo", "Complejo")
                        .WithMany()
                        .HasForeignKey("IDComplejo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Complejo");
                });

            modelBuilder.Entity("ProyectoBase.Models.AmenityConfig", b =>
                {
                    b.HasOne("ProyectoBase.Models.Amenity", "Amenity")
                        .WithOne("Config")
                        .HasForeignKey("ProyectoBase.Models.AmenityConfig", "IDAmenity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");
                });

            modelBuilder.Entity("ProyectoBase.Models.Complejo", b =>
                {
                    b.HasOne("ProyectoBase.Models.Consorcio", "Consorcio")
                        .WithMany()
                        .HasForeignKey("IDConsorcio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consorcio");
                });

            modelBuilder.Entity("ProyectoBase.Models.Inquilino", b =>
                {
                    b.HasOne("ProyectoBase.Models.UnidadHabitacional", "UnidadHabitacional")
                        .WithMany()
                        .HasForeignKey("IDUnidadHabitacional")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UnidadHabitacional");
                });

            modelBuilder.Entity("ProyectoBase.Models.Invitado", b =>
                {
                    b.HasOne("ProyectoBase.Models.UnidadHabitacional", "UnidadHabitacional")
                        .WithMany()
                        .HasForeignKey("IDUnidadHabitacional")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UnidadHabitacional");
                });

            modelBuilder.Entity("ProyectoBase.Models.UnidadHabitacional", b =>
                {
                    b.HasOne("ProyectoBase.Models.Complejo", "Complejo")
                        .WithMany()
                        .HasForeignKey("IDComplejo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Complejo");
                });

            modelBuilder.Entity("ProyectoBase.Models.Amenity", b =>
                {
                    b.Navigation("Config");
                });
#pragma warning restore 612, 618
        }
    }
}
