// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProyectoBase.Models;

#nullable disable

namespace ProyectoBase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProyectoBase.Models.Amenity", b =>
                {
                    b.Property<int>("IDAmenity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDAmenity"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("DISPONIBLE");

                    b.Property<int>("IDComplejo")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IDAmenity");

                    b.HasIndex("IDComplejo", "Nombre")
                        .IsUnique();

                    b.ToTable("PB_Amenity", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.AmenityConfig", b =>
                {
                    b.Property<int>("IDAmenityConfig")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDAmenityConfig"));

                    b.Property<int>("DuracionBloqueMinutos")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("HorarioFin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HorarioInicio")
                        .HasColumnType("time without time zone");

                    b.Property<int>("IDAmenity")
                        .HasColumnType("integer");

                    b.Property<int>("LimiteReservasMesUnidad")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiereAprobacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Tarifa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("TiempoLimpiezaMinutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("IDAmenityConfig");

                    b.HasIndex("IDAmenity")
                        .IsUnique();

                    b.ToTable("PB_AmenityConfig", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.AuditLog", b =>
                {
                    b.Property<int>("IDAuditLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDAuditLog"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Detalle")
                        .HasColumnType("text");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("EntidadId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IDAuditLog");

                    b.ToTable("PB_AuditLog", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.Complejo", b =>
                {
                    b.Property<int>("IDComplejo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDComplejo"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("IDConsorcio")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IDComplejo");

                    b.HasIndex("IDConsorcio", "Nombre")
                        .IsUnique();

                    b.ToTable("PB_Complejo", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.Consorcio", b =>
                {
                    b.Property<int>("IDConsorcio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDConsorcio"));

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("TieneGuardiaDedicado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("IDConsorcio");

                    b.HasIndex("Cuit")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("PB_Consorcio", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.Incidencia", b =>
                {
                    b.Property<int>("IDIncidencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDIncidencia"));

                    b.Property<decimal?>("CostoEstimado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DetalleResolucion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("timestamptz");

                    b.Property<int>("IDAmenity")
                        .HasColumnType("integer");

                    b.Property<int>("IDUnidadHabitacional")
                        .HasColumnType("integer");

                    b.HasKey("IDIncidencia");

                    b.HasIndex("IDAmenity");

                    b.HasIndex("IDUnidadHabitacional");

                    b.ToTable("PB_Incidencia", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.Inquilino", b =>
                {
                    b.Property<int>("IDInquilino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDInquilino"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Celular")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("IDUnidadHabitacional")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("IDInquilino");

                    b.HasIndex("IDUnidadHabitacional");

                    b.ToTable("PB_Inquilino", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.InvitacionUsuario", b =>
                {
                    b.Property<int>("IDInvitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDInvitacion"));

                    b.Property<string>("EmailDestino")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDIENTE");

                    b.Property<DateTime?>("FechaAceptacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("IDComplejo")
                        .HasColumnType("integer");

                    b.Property<int?>("IDConsorcio")
                        .HasColumnType("integer");

                    b.Property<int?>("IDUnidadHabitacional")
                        .HasColumnType("integer");

                    b.Property<int?>("IDUsuarioCreador")
                        .HasColumnType("integer");

                    b.Property<string>("RolDestino")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TelefonoDestino")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IDInvitacion");

                    b.HasIndex("IDComplejo");

                    b.HasIndex("IDConsorcio");

                    b.HasIndex("IDUnidadHabitacional");

                    b.HasIndex("IDUsuarioCreador");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("PB_InvitacionUsuario", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.Invitado", b =>
                {
                    b.Property<int>("IDInvitado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDInvitado"));

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("FechaExpiracion")
                        .HasColumnType("date");

                    b.Property<int>("IDUnidadHabitacional")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Patente")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IDInvitado");

                    b.HasIndex("IDUnidadHabitacional", "Dni")
                        .IsUnique();

                    b.ToTable("PB_Invitado", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.ListaEspera", b =>
                {
                    b.Property<int>("IDListaEspera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDListaEspera"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasDefaultValue("ESPERANDO");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("FechaNotificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly>("FechaUso")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("IDAmenity")
                        .HasColumnType("integer");

                    b.Property<int>("IDUnidadHabitacional")
                        .HasColumnType("integer");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoExpiracion")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Posicion")
                        .HasColumnType("integer");

                    b.HasKey("IDListaEspera");

                    b.HasIndex("IDAmenity");

                    b.HasIndex("IDUnidadHabitacional");

                    b.HasIndex("IDUsuario");

                    b.ToTable("PB_ListaEspera", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.MantenimientoProgramado", b =>
                {
                    b.Property<int>("IDMantenimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDMantenimiento"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("IDAmenity")
                        .HasColumnType("integer");

                    b.Property<string>("Recurrencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IDMantenimiento");

                    b.HasIndex("IDAmenity");

                    b.ToTable("PB_MantenimientoProgramado", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.NotificacionIntento", b =>
                {
                    b.Property<int>("IDIntento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDIntento"));

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("Entregado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("EntregadoEn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EnviadoEn")
                        .HasColumnType("timestamptz");

                    b.Property<int>("IDNotificacion")
                        .HasColumnType("integer");

                    b.HasKey("IDIntento");

                    b.ToTable("PB_NotificacionIntento", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.Persona", b =>
                {
                    b.Property<int>("IDPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDPersona"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Celular")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("IDPersona");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("PB_Persona", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.PoliticaCancelacionTramo", b =>
                {
                    b.Property<int>("IDTramo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDTramo"));

                    b.Property<int>("HorasAntesDesde")
                        .HasColumnType("integer");

                    b.Property<int>("HorasAntesHasta")
                        .HasColumnType("integer");

                    b.Property<int?>("IDAmenityConfig")
                        .HasColumnType("integer");

                    b.Property<decimal>("PorcentajePenalidad")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("IDTramo");

                    b.HasIndex("IDAmenityConfig");

                    b.ToTable("PB_PoliticaCancelacionTramo", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.Reserva", b =>
                {
                    b.Property<int>("IDReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDReserva"));

                    b.Property<int>("CantidadInvitados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("CheckInFecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("CheckInRealizado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamptz");

                    b.Property<DateOnly>("FechaUso")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("IDAmenity")
                        .HasColumnType("integer");

                    b.Property<int>("IDUnidadHabitacional")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoRetenido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0.00m);

                    b.HasKey("IDReserva");

                    b.HasIndex("IDAmenity");

                    b.HasIndex("IDUnidadHabitacional");

                    b.ToTable("PB_Reserva", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.Rol", b =>
                {
                    b.Property<int>("IDRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDRol"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IDRol");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("PB_Rol", (string)null);

                    b.HasData(
                        new
                        {
                            IDRol = 1,
                            Codigo = "SUPER_ADMINISTRADOR",
                            Descripcion = "Acceso total cross-tenant",
                            Nombre = "Super Administrador"
                        },
                        new
                        {
                            IDRol = 2,
                            Codigo = "ADMINISTRADOR_AVANZADO",
                            Descripcion = "Gestión completa del consorcio",
                            Nombre = "Administrador Avanzado"
                        },
                        new
                        {
                            IDRol = 3,
                            Codigo = "ADMINISTRADOR_LIVIANO",
                            Descripcion = "Operativo día a día sin guardia",
                            Nombre = "Administrador Liviano"
                        },
                        new
                        {
                            IDRol = 4,
                            Codigo = "GUARDIA",
                            Descripcion = "Control de accesos y portería",
                            Nombre = "Guardia / Seguridad"
                        },
                        new
                        {
                            IDRol = 5,
                            Codigo = "PROPIETARIO",
                            Descripcion = "Dueño de unidad con supervisión",
                            Nombre = "Propietario"
                        },
                        new
                        {
                            IDRol = 6,
                            Codigo = "INQUILINO",
                            Descripcion = "Residente operativo de unidad",
                            Nombre = "Inquilino"
                        },
                        new
                        {
                            IDRol = 7,
                            Codigo = "INVITADO",
                            Descripcion = "Acceso temporal con vigencia acotada",
                            Nombre = "Invitado"
                        });
                });

            modelBuilder.Entity("ProyectoBase.Models.UnidadHabitacional", b =>
                {
                    b.Property<int>("IDUnidadHabitacional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDUnidadHabitacional"));

                    b.Property<int>("ContadorInfracciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("DebeExpensas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("EstadoUnidad")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ACTIVA");

                    b.Property<int>("IDComplejo")
                        .HasColumnType("integer");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("SaldoActual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("IDUnidadHabitacional");

                    b.HasIndex("IDComplejo", "Identificador")
                        .IsUnique();

                    b.ToTable("PB_UnidadHabitacional", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.Usuario", b =>
                {
                    b.Property<int>("IDUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDUsuario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("INQUILINO");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IDUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("PB_Usuario", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.UsuarioRol", b =>
                {
                    b.Property<int>("IDUsuarioRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDUsuarioRol"));

                    b.Property<int>("IDRol")
                        .HasColumnType("integer");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("integer");

                    b.HasKey("IDUsuarioRol");

                    b.HasIndex("IDRol");

                    b.HasIndex("IDUsuario", "IDRol")
                        .IsUnique();

                    b.ToTable("PB_UsuarioRol", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.UsuarioUnidad", b =>
                {
                    b.Property<int>("IDUsuarioUnidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDUsuarioUnidad"));

                    b.Property<bool>("EsOcupanteActual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("EstadoRelacion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("VIGENTE");

                    b.Property<int>("IDUnidadHabitacional")
                        .HasColumnType("integer");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("TipoRelacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IDUsuarioUnidad");

                    b.HasIndex("IDUnidadHabitacional");

                    b.HasIndex("IDUsuario");

                    b.ToTable("PB_UsuarioUnidad", (string)null);
                });

            modelBuilder.Entity("ProyectoBase.Models.Amenity", b =>
                {
                    b.HasOne("ProyectoBase.Models.Complejo", "Complejo")
                        .WithMany()
                        .HasForeignKey("IDComplejo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Complejo");
                });

            modelBuilder.Entity("ProyectoBase.Models.AmenityConfig", b =>
                {
                    b.HasOne("ProyectoBase.Models.Amenity", "Amenity")
                        .WithOne("Config")
                        .HasForeignKey("ProyectoBase.Models.AmenityConfig", "IDAmenity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");
                });

            modelBuilder.Entity("ProyectoBase.Models.Complejo", b =>
                {
                    b.HasOne("ProyectoBase.Models.Consorcio", "Consorcio")
                        .WithMany()
                        .HasForeignKey("IDConsorcio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consorcio");
                });

            modelBuilder.Entity("ProyectoBase.Models.Incidencia", b =>
                {
                    b.HasOne("ProyectoBase.Models.Amenity", "Amenity")
                        .WithMany()
                        .HasForeignKey("IDAmenity")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoBase.Models.UnidadHabitacional", "UnidadHabitacional")
                        .WithMany()
                        .HasForeignKey("IDUnidadHabitacional")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("UnidadHabitacional");
                });

            modelBuilder.Entity("ProyectoBase.Models.Inquilino", b =>
                {
                    b.HasOne("ProyectoBase.Models.UnidadHabitacional", "UnidadHabitacional")
                        .WithMany()
                        .HasForeignKey("IDUnidadHabitacional")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UnidadHabitacional");
                });

            modelBuilder.Entity("ProyectoBase.Models.InvitacionUsuario", b =>
                {
                    b.HasOne("ProyectoBase.Models.Complejo", "Complejo")
                        .WithMany()
                        .HasForeignKey("IDComplejo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProyectoBase.Models.Consorcio", "Consorcio")
                        .WithMany()
                        .HasForeignKey("IDConsorcio")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProyectoBase.Models.UnidadHabitacional", "UnidadHabitacional")
                        .WithMany()
                        .HasForeignKey("IDUnidadHabitacional")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProyectoBase.Models.Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("IDUsuarioCreador")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Complejo");

                    b.Navigation("Consorcio");

                    b.Navigation("UnidadHabitacional");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("ProyectoBase.Models.Invitado", b =>
                {
                    b.HasOne("ProyectoBase.Models.UnidadHabitacional", "UnidadHabitacional")
                        .WithMany()
                        .HasForeignKey("IDUnidadHabitacional")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UnidadHabitacional");
                });

            modelBuilder.Entity("ProyectoBase.Models.ListaEspera", b =>
                {
                    b.HasOne("ProyectoBase.Models.Amenity", "Amenity")
                        .WithMany()
                        .HasForeignKey("IDAmenity")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoBase.Models.UnidadHabitacional", "UnidadHabitacional")
                        .WithMany()
                        .HasForeignKey("IDUnidadHabitacional")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoBase.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("UnidadHabitacional");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoBase.Models.MantenimientoProgramado", b =>
                {
                    b.HasOne("ProyectoBase.Models.Amenity", "Amenity")
                        .WithMany()
                        .HasForeignKey("IDAmenity")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Amenity");
                });

            modelBuilder.Entity("ProyectoBase.Models.PoliticaCancelacionTramo", b =>
                {
                    b.HasOne("ProyectoBase.Models.AmenityConfig", "AmenityConfig")
                        .WithMany()
                        .HasForeignKey("IDAmenityConfig")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AmenityConfig");
                });

            modelBuilder.Entity("ProyectoBase.Models.Reserva", b =>
                {
                    b.HasOne("ProyectoBase.Models.Amenity", "Amenity")
                        .WithMany()
                        .HasForeignKey("IDAmenity")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoBase.Models.UnidadHabitacional", "UnidadHabitacional")
                        .WithMany()
                        .HasForeignKey("IDUnidadHabitacional")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("UnidadHabitacional");
                });

            modelBuilder.Entity("ProyectoBase.Models.UnidadHabitacional", b =>
                {
                    b.HasOne("ProyectoBase.Models.Complejo", "Complejo")
                        .WithMany()
                        .HasForeignKey("IDComplejo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Complejo");
                });

            modelBuilder.Entity("ProyectoBase.Models.UsuarioRol", b =>
                {
                    b.HasOne("ProyectoBase.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IDRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoBase.Models.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoBase.Models.UsuarioUnidad", b =>
                {
                    b.HasOne("ProyectoBase.Models.UnidadHabitacional", "UnidadHabitacional")
                        .WithMany()
                        .HasForeignKey("IDUnidadHabitacional")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoBase.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnidadHabitacional");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoBase.Models.Amenity", b =>
                {
                    b.Navigation("Config");
                });

            modelBuilder.Entity("ProyectoBase.Models.Usuario", b =>
                {
                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
